model_config: 
  model_name: muscall
  projection_dim: 512             # dimensionality of the multimodal projection layer
  temperature: null
  clap:
    clap_ckpt: /Music-Tri-Modal/music_audioset_epoch_15_esc_90.14.pt
    text_hidden_size: 512
    audio_hidden_size: 512
  midi:
    midi_dic: /Music-Tri-Modal/muscall/modules/MidiBERT/CP.pkl
    max_seq_len: 512
    hidden_size: 768
  loss: clip                      # one of [clip, weighted_clip]
