dataset_config:
  dataset_name: audiocaptionmidi # dataset name that you will use
  data_dir: ${env.data_root}/datasets/${dataset_config.dataset_name}
  # Caption configs
  text:
  audio:
    sr: 48000
    crop_length: 60 # 曲の長さ（秒）
    offset: 0.1
    random_crop: true
    augment: false
    p_noise: 0.3
    p_pitch_shift: 0.4
  midi:
    size_dim0: 10